unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",foot:Tc"
set -g terminal-features "foot:clipboard"

set -g mouse on
set -g history-limit 10000

set -g base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g focus-events on

set -g status-interval 5
set -g status-fg white
set -g status-bg default
set -g status-left " #[bold]#S "
set -g status-right " #[fg=yellow]#(date '+%H:%M') "
set -g status-right-length 40
set -g window-status-current-style "bold,fg=cyan"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-position top

setw -g mode-keys vi
setw -g monitor-activity on
set -g visual-activity off

bind r source-file ~/.config/tmux/tmux.conf \; display "tmux reloaded"
bind | split-window -h -c '#{pane_current_path}'
bind _ split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
