unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",foot:Tc"
set -g terminal-features "foot:clipboard"

set -g mouse on
set -g history-limit 10000

set -g base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g focus-events on

set -g status-interval 5
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left " #[bold,fg=#cba6f7]#S #[fg=#45475a]│ "
set -g status-right " #{?client_key_table,#[fg=#89dceb]TABLE:#{client_key_table} ,}#{?client_prefix,#[fg=#cba6f7]LEADER ,}#[fg=#f9e2af]#(date '+%H:%M') "
set -g status-right-length 60
set -g window-status-style "fg=#7f849c,bg=#1e1e2e"
set -g window-status-format " #I:#W "
set -g window-status-current-style "bold,fg=#cba6f7,bg=#313244"
set -g window-status-current-format " #I:#W "
set -g window-status-separator " "
set -g status-position top

setw -g mode-keys vi
setw -g monitor-activity on
set -g visual-activity off

bind R source-file ~/.config/tmux/tmux.conf \; display "tmux reloaded"

unbind -T prefix H
unbind -T prefix J
unbind -T prefix K
unbind -T prefix L

bind r switch-client -T resize
bind -T resize h resize-pane -L 3
bind -T resize j resize-pane -D 3
bind -T resize k resize-pane -U 3
bind -T resize l resize-pane -R 3
bind -T resize Escape switch-client -T root
bind -T resize C-Space switch-client -T root

bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind o select-pane -t:.+
bind x confirm-before kill-pane
bind f resize-pane -Z
bind s display-panes
bind t choose-tree -w
bind [ copy-mode
bind ] paste-buffer
bind e command-prompt -I "#W" "rename-window '%%'"
bind & confirm-before -p "kill-window? (y/n)" kill-window

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @resurrect-capture-pane-contents 'off'
set -g @resurrect-processes '~nvim -> nvim'
set -g @resurrect-strategy-nvim 'session'

bind C-f run-shell 'tmux-sessionizer'

run '~/.tmux/plugins/tpm/tpm'
